version: '3'

services:
  reverse-proxy:
    image: traefik:v2.10
    ports:
      - "8090:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf:/etc/traefik
      - ./plugins/req-preprocess:/plugins-local/src/github.com/SwanHubX/req-preprocess