http:
  routers:
    to-whoami:
      rule: "PathPrefix(`/api`)"
      service: whoami
      middlewares:
        - "preprocess"
  services:
    whoami:
      loadBalancer:
        servers:
          - url: "http://192.168.31.60:8008/"
  middlewares:
    preprocess:
      plugin:
        rpp:
          AuthUrl: "http://192.168.31.60:3000/auth/identity"
          Key: |
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA61/d80yCyzy70PtWcslU
            ezWOu02Q6GbtUesCD6mnSiBeocbQGdXejvLRbSrwA8DXyRX8fvg5TPUCFCUza8DW
            J995UhsyIjg6w9ubNA7LbddUDLfREs7pBP7lcjU0LG17LAm9vdusgF6wb7UgGctA
            201uiJ+NilHgf94QaSqtwjaAw6maIdACllxUMj4ZW/4lfJc6pm8YDyOVM5+eE+jE
            yiPoLhkMuROvY9SONe0oMZRnj2O2fwjEPzwXMaWnTF7Em2cJaysgnnDA4dcxa64a
            b1imJPMYq+AAulbAdIiz6YZoUNT12M/zgBgBJcsur4Ss5xFceJMB1N12cjfqA+S3
            7QIDAQAB
            -----END PUBLIC KEY-----
