name: release version

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: release version from tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: tar -zcvf req-preprocess.tar.gz .traefik.yml go.mod preprocess.go README.md
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{ github.event.head_commit.message }}
          files: |
            req-preprocess.tar.gz
